name: SurvivalGames
version: 0.6.7
main: com.thundergemios10.survivalgames.SurvivalGames
## Authors ##
authors: [Double0Negative, ThunderGemios10]
website: thundergemios10.com
description: Fully Automated Hunger Games Plugin!
depend: [WorldEdit]

commands:
    survivalgames:
        description: Survival Games Command
        usage: /sg <command> <args>
        aliases: [sg, hungergames, hg]

